### ISSUE TITLE
There's and issue when Open the folder

### ISSUE THREAD

**Issue by benyaminl** [getgrav/grav-plugin-data-manager#10]
https://files.gitter.im/getgrav/grav/B8LM/blob

https://files.gitter.im/getgrav/grav/Rn1W/blob

when opening directly working but opening folder failed. I don't know why

**Comment by flaviocopes** [comment]
Please post all the information needed to recreate the issue, paste the folder files content, or better zip them and upload here the part of the user/data content that is breaking it

**Comment by benyaminl** [comment]
[data.zip](https://github.com/getgrav/grav-plugin-data-manager/files/344363/data.zip)
That's the folder

**Comment by flaviocopes** [comment]
Thanks.

So, some data is not formatted properly as YAML.

Data Manager can read YAML-formatted files, and some of yours contain this

```
Contact form 

name: *****
email: *****
```

Some others are properly formatter, simply remove the bad ones.
