### ISSUE TITLE
Error because of 'licenses.yaml'

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-data-manager#12]
I installed the Data Manger 1.0.6 plugin and with it the file `licenses.yaml` gets created in the `data` folder. If i then try to view the data in admin, i get this error
`FilesystemIterator::__construct(/Users/dave/Sites/user/data/licenses.yaml): failed to open dir: Not a directory`

After deleting `licenses.yaml` the plugin works again.

BTW: The file is empty

**Comment by rhukster** [comment]
we'll get this sorted to ignore that file.
