### ISSUE TITLE
Always one 'notificaton' item present

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-data-manager#13]
With data manager 1.0.6 and 1.0.7 i have this issue:
In the `data` folder there is a folder `notifications` and in that folder is a file called `endogen.yaml`. Endogen is my username in that Grav installation.

The content of that file is `- '10'`

I don't understand what the purpose of that file is and also i'm not sure what `Notifications` are in that context.

**Comment by Endogen** [comment]
Any chance to let me know what these notifications are? I didn't find anything on the topic here in the plugin repo or in grav docs. It's not only that the file exists. It also gets shown in the admin plugin. Why? What is that?

**Comment by flaviocopes** [comment]
That file is created by the Admin plugin. It stores information on which notifications you already marked as read, so you won't see them again in the future. They are stored in the user/data folder so when moving a site, you don't lose this information and won't see notifications you already marked as read.

Data Manager is simply a plugin to help navigate items in the `data` folder. It did not create them, but yes they are shown inside the plugin, we should ignore that folder.

**Comment by Endogen** [comment]
Got it! Thanks. I didn't know that "notifications" means the grav new-version-notifications.
