### ISSUE TITLE
Nothing appears in the data manager

### ISSUE THREAD

**Issue by benkuper** [getgrav/grav-plugin-data-manager#16]
Hello,
i have a grav installation in a subfolder of my website, everything is working, the plugin is successfully installed and enabled but when i put data in my /user/data folder (zip files), i see nothing.
i've tried with jpg and png files to check if it was an extension problem, but i don't see anything in the data manager in the admin panel...

To be sure i have chmod 777 the user and the data folder but still nothing. 

any idea ?

Also if it can helps, i've installed the download-counter plugin which should create some file or folder in the /user/data directory, but there is nothing as well.

**Comment by flaviocopes** [comment]
The `user/data` folder generally hosts folders and within those folders, yaml files.

Any form that saves data to disk follows this structure, including the Comments plugin. See https://github.com/getgrav/grav-plugin-data-manager#configuration

Data Manager follows this convention, it's not a file browser, but a YAML file interpreter.

Not familiar with the download counter plugin, but seems it follows this structure, so it should work. Is there anything in the `user/data/downloads-counter` folder it creates?
