### ISSUE TITLE
Value of hidden field is displayed in thank you page

### ISSUE THREAD

**Issue by juliendude** [getgrav/grav-plugin-data-manager#17]
Hi,

I set up a very simple and basic form as shown in the grav documentation site.

I added the following hidden field:
```
- name: user-name
          type: hidden
          default: my-value
```
The form works fine, the data is saved and accessible via the data manager. But on the thank you page which is also the basic one as shown in the documentation; the value of the hidden field is showing in the list of submitted content.

**Comment by flaviocopes** [comment]
Hi, looks like an issue in the Form plugin. Hidden fields should save, but not be shown to the end user.

The default `data.html.twig` template should have `{% if field.type != 'hidden' %}` [inside this for loop](https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/default/data.html.twig#L2).

In the meantime you can edit that file in your own template as well (`yourtheme/templates/forms/data.html.twig`)
