### ISSUE TITLE
Nothing appears on the page.

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-data-manager#19]
Hello.
I have sucessfully installed this plugin but when I go to the "Data Manager" page on the admin board, nothing happend. There is a blank page.
Please help me.
Thank you,
Reotip.

**Comment by flaviocopes** [comment]
Is there anything in your user/data folder? Data Manager will show the content present in that folder. If there is nothing, that's probably the cause.

**Comment by ghost** [comment]
Sorry, I wasn't paying attention to issues anymore.
Thanks anyway for your answer, it was really useful.
