### ISSUE TITLE
Grav Data Manager User Permissions

### ISSUE THREAD

**Issue by sjclark** [getgrav/grav-plugin-data-manager#23]
Trying to figure out how to reference permissions for users to this - it seems unless I have SUPER set then access is not allowed? I've had a look through the source but couldn't find anything. Might be good if this could be appended to the README? Thanks =)

**Comment by grantholle** [comment]
Yes, would be helpful if it had a specific user permission that we could give instead of super

**Comment by KevinTessier** [comment]
Hi, 
you can add permission in accounts/user1.yaml or config/groups.yaml. 
Add data-manager: 'true'
normally it works
