### ISSUE TITLE
Public access to CSV export

### ISSUE THREAD

**Issue by philipptempel** [getgrav/grav-plugin-data-manager#28]
Apparently it seems the URL to download the CSV is publicly available. Just checked it by copying the link location of the "Download as CSV" file and pasting it in a private window. This lead me to being able to download the CSV file **without authentication**.

I see this as quite a security flaw, especially since the download URL does not change. Not sure if a robot or web crawler could find the URL, but I guess it's just a matter of time till the URL is crawled.

**Comment by w00fz** [comment]
At last, this is now implemented (#35)
