### ISSUE TITLE
Replace Data Manager menu icon

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-data-manager#3]
Pages menu icon and Data Manager menu icons looking similar. I think it can be better to replace current Data Manager menu icon with fa-database icon.
Now:
![01](https://cloud.githubusercontent.com/assets/8279974/9931601/c02ce9b8-5d45-11e5-8e72-e6d444b08268.png)
After:
![02](https://cloud.githubusercontent.com/assets/8279974/9931606/cb75d62c-5d45-11e5-864b-74ad0bcfbaf7.png)

**Comment by flaviocopes** [comment]
Good suggestion!
