### ISSUE TITLE
Plugin abandoned?

### ISSUE THREAD

**Issue by aricooperdavis** [getgrav/grav-plugin-data-manager#39]
Hi,

Has this plugin been abandoned by Team Grav? There have been no updates for 3 years despite open pull requests that add functionality without breaking backwards compatability.

I understand that there is only so much time for development of these things, and am happy to get involved, but only if my pull requests won't be wasted!

Thanks,
Ari

**Comment by w00fz** [comment]
It's not abandoned, we just have a lot on our plate :) I have now included your PR for next release. Thanks!

**Comment by aricooperdavis** [comment]
Thank you! I'm sorry for chasing - I just didn't know if future changes to Grav were going to replace the data manager or something. I appreciate the incredible commitment of the team to this excellent open source project.
