### ISSUE TITLE
Page count changes while browsing data

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-data-manager#5]
Look at the page counter:
![01](https://cloud.githubusercontent.com/assets/8279974/9933838/9430bd92-5d56-11e5-811f-d063c434a519.png)
![02](https://cloud.githubusercontent.com/assets/8279974/9933849/adad4efc-5d56-11e5-8523-0dd6d9712b5e.png)
![03](https://cloud.githubusercontent.com/assets/8279974/9933858/b137f5c2-5d56-11e5-9cc5-7602d1eca1a1.png)

**Comment by flaviocopes** [comment]
Ah I guess the data-manager admin pages gets counted too, thanks for reporting - didn't notice!
